name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}] # once a week at 00:00
  workflow_dispatch:
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          user: maksmakuta
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Kiev
          plugin_calendar: yes
          plugin_calendar_limit: 3

# Your GitHub token
# The following scopes are required:
#  - public_access (default scope)
#  - public_repo
#  - read:project
# The following additional scopes may be required:
#  - read:org      (for organization related metrics)
#  - read:user     (for user related data)
#  - read:packages (for some packages related data)
#  - repo          (optional, if you want to include private repositories)
